version: '3.8'
services:
  soc:
    container_name: soc
    build:
      context: ./
      dockerfile: Dockerfile.app
    depends_on:
      - mongo
    restart: unless-stopped
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - '27017-27019:27017-27019'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'admin'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    volumes:
      - /data:/data/db/
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    command:
#      - '--auth'
