version: '3.8'
services:
  soc:
    container_name: soc
    build:
      context: ./
      dockerfile: Dockerfile.app
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.16.0.12
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongodb
    ports:
    - '27017-27019:27017-27019'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'admin'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    networks:
      net:
        ipv4_address: 172.16.0.13
    volumes:
      - ./data:/data/db/
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command:
      - '--auth'
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24