version: '3.8'
services:
  soc:
    container_name: soc
#    build:
#      context: ./
#      dockerfile: Dockerfile.app
    image: sskuratov/soc
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - redis-net
  redis:
    image: bitnami/redis
    container_name: redis
    ports:
    - 6379:6379
    restart: always
    environment:
    - REDIS_REPLICATION_MODE=master
    command: redis-server --requirepass user2412
    volumes:
      - redis-data:/data
    networks:
      - redis-net
volumes:
  redis-data:
networks:
  redis-net:
